### ISSUE TITLE
thread-safety

### ISSUE THREAD

**Issue by nsajko** [JuliaMath/DoubleFloats.jl#157]
`setprecision` seems to be used a lot in this package. This might be a problem because, as [documented](https://docs.julialang.org/en/v1/base/numbers/#Base.MPFR.setprecision), `setprecision` isn't thread-safe.

Personally, I'd think that the best practice would be not to use `setprecision` at all in a low-level package like this and instead leave this to the user.

If nothing else, if a function isn't thread-safe, that should be documented.

**Comment by JeffreySarnoff** [comment]
Actually, setprecision is only used with string input, and the value of precision on entry is always restored -- it is left to the user outside of doing something like `Double64("123.131231534542412342424234242424234")` and in that case, because (as you say) it may be manipulated outside and could be set too small to properly convert the string, temporarily resetting the precision is necessary.

There are a few other uses in triple.jl -- however there it is for the same purpose, handling string input. Moreover, that source file is not used in computations -- and is certainly not available to be called by users of the package.

I hope this helps.  Thank you for your attention.
